queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Run Unit and UI tests
      - check-success=license/cla

pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: squash
        name: default

  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"