queue_rules:
  - name: default
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Run Unit and UI tests
      - check-success=license/cla
    merge_method: squash

pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
