trigger:
- develop

pr:
- develop

pool:
  name: 'Hosted VS2019'
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

variables:
  GitVersion.SemVer: ''

steps:

- task: PowerShell@2
  displayName: Setting up Swedbank connection setting token
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $Token = "$(SwedbankPayConnectionSettings.Token)"    
      [System.Environment]::SetEnvironmentVariable("SwedbankPayConnectionSettings.Token", $Token, "User")

- task: GitVersion@5 
  displayName: GitVersion
  inputs:
    versionSpec: '5.x'
    runtime: 'core'
    useConfigFile: true
    configFilePath: GitVersion.yml


- task: UseDotNet@2
  displayName: 'Setting up framework for build'
  inputs:
    packageType: 'sdk'
    version: '3.1.101'
    installationPath: $(Agent.TempDirectory)/dotnet

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  displayName: 'Restoring packages'
  inputs:
     command: 'restore'
     restoreSolution: '$(Build.SourcesDirectory)\src\SwedbankPay.Sdk.sln'
     feedsToUse: 'select'


- task: DotNetCoreCLI@2
  displayName: 'Build solution for .net core projects'
  inputs:
    command: 'build'
    projects: |
      **/*.sln
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersionV2)'


- task: MSBuild@1
  displayName: 'Build system tests project'
  inputs:
    solution: '$(Build.SourcesDirectory)\src\Samples\Sample.AspNetCore.SystemTests\Sample.AspNetCore.SystemTests.csproj'
    platform: AnyCPU
    configuration: $(buildConfiguration)
  enabled: false

- task: DotNetCoreCLI@2
  displayName: 'Run unit / integration tests'
  inputs:
    command: test
    projects: '$(Build.SourcesDirectory)\src\SwedbankPay.Sdk.Tests\SwedbankPay.Sdk.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create release'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--output $(Build.ArtifactStagingDirectory) --configuration $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersionV2)'


- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package - $(buildConfiguration) Version'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)\src\SwedbankPay.Sdk\SwedbankPay.Sdk.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
    nobuild: true
    versioningScheme: 'off'
    buildProperties: 'PackageVersion=$(GitVersion.NuGetVersionV2)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish .net core build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish system test project build artifacts'
  inputs:
    PathtoPublish: 'src\Samples\Sample.AspNetCore.SystemTests'
    ArtifactName: 'SystemTests'
    publishLocation: 'Container'



