name: Pro

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  release:
    types:
      - created

jobs:
  callVersion:
    name: Create version number
    uses: ./.github/workflows/template_version.yml
  
  callBuild:
    needs: [callVersion]
    name: Build and publish artifact
    uses: ./.github/workflows/template_build.yml
    secrets: inherit 
    with:
      Configuration: Release
      NUGETVERSIONV2: ${{ needs.callVersion.outputs.NUGETVERSIONV2 }} 
      SlnPath: ./src/SwedbankPay.Sdk.sln
      SdkCsprojPath: ./src/SwedbankPay.Sdk.Infrastructure/SwedbankPay.Sdk.Infrastructure.csproj
      SampleSiteCsprojPath: ./src/Samples/Sample.AspNetCore/Sample.AspNetCore.csproj
      UnitTestsCsprojPath: ./src/SwedbankPay.Sdk.Tests/SwedbankPay.Sdk.Tests.csproj
