name: Create version number

on:
  workflow_call:
    outputs:
      NUGETVERSIONV2:
        description: "Nuget version"
        value: ${{ jobs.version.outputs.NUGETVERSIONV2 }}

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      NUGETVERSIONV2: ${{ steps.gitversion.outputs.NUGETVERSIONV2 }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0   

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@51d325634925d7d9ce0a7efc2c586c0bc2b9eee6 # v3.2.1
        with:
          versionSpec: '5.x'
 
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@51d325634925d7d9ce0a7efc2c586c0bc2b9eee6 # v3.2.1